<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jincheng Li, Mason Spikula, Quinn Hughes">

<title>DataPrep</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="DataPrep_files/libs/clipboard/clipboard.min.js"></script>
<script src="DataPrep_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="DataPrep_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="DataPrep_files/libs/quarto-html/popper.min.js"></script>
<script src="DataPrep_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="DataPrep_files/libs/quarto-html/anchor.min.js"></script>
<link href="DataPrep_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="DataPrep_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="DataPrep_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="DataPrep_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="DataPrep_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">DataPrep</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jincheng Li, Mason Spikula, Quinn Hughes </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(purrr)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="loading-datasets" class="level3">
<h3 class="anchored" data-anchor-id="loading-datasets">Loading Datasets</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>cell_per_100 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"cell_phones_per_100_people.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 194 Columns: 67
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): geo, name
dbl (45): 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, ...
lgl (20): 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, ...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>gap <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'gapminder_2025.csv'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 193 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): geo, name, world_4region, landlocked
dbl (3): gdp, life_exp, log_gdp

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>hdi <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'hdi_human_development_index.csv'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 192 Columns: 36
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): geo, name
dbl (34): 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, ...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>maternal_mortality <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'maternal_mortality_ratio_who.csv'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 179 Columns: 23
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): geo, name
dbl  (5): 1990, 1995, 2000, 2005, 2010
lgl (16): 1991, 1992, 1993, 1994, 1996, 1997, 1998, 1999, 2001, 2002, 2003, ...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>daily_inc <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'mincpcap_cppp (1).csv'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 193 Columns: 303
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr   (2): geo, name
dbl (301): 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810,...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>engy_use_pctg <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'residential_energy_use_percent.csv'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 133 Columns: 53
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): geo, name
dbl (51): 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, ...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</section>
<section id="pulling-data-from-year-we-want-and-cleaning-it" class="level3">
<h3 class="anchored" data-anchor-id="pulling-data-from-year-we-want-and-cleaning-it">Pulling data from year we want and Cleaning it</h3>
<p>We use 2010 data. Response: Daily income is quantitative and measures average income per person per day in dollars. The quantitative predictors are phones per 100 people, residential energy use as a percentage of total energy use, HDI, and maternal deaths per 100,000 live births. Income, phones, and mortality are nonnegative; Landlocked status is categorical: coastline or landlocked. 194 countries in the combined data, missing are 1 for income, 1 for subscriptions, 61 for energy, 4 for HDI, and 15 for mortality; landlocked status and country name are each missing for 1 country, geo codes are complete. Missing values overlap across countries. Removing incomplete rows = 132 countries and excludes 62.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>cell_2010 <span class="ot">&lt;-</span> cell_per_100 <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(geo, <span class="st">`</span><span class="at">2010</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">cell_phones_per_100_ppl =</span> <span class="st">`</span><span class="at">2010</span><span class="st">`</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>engy_2010 <span class="ot">&lt;-</span> engy_use_pctg <span class="sc">|&gt;</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(geo, <span class="st">`</span><span class="at">2010</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">residential_energy_use_pctg =</span> <span class="st">`</span><span class="at">2010</span><span class="st">`</span>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>hdi_2010 <span class="ot">&lt;-</span> hdi <span class="sc">|&gt;</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(geo, <span class="st">`</span><span class="at">2010</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">human_development_ind =</span> <span class="st">`</span><span class="at">2010</span><span class="st">`</span>)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>mat_mort_2010 <span class="ot">&lt;-</span> maternal_mortality <span class="sc">|&gt;</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(geo, <span class="st">`</span><span class="at">2010</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">maternal_mortality =</span> <span class="st">`</span><span class="at">2010</span><span class="st">`</span>)</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>daily_inc_2010 <span class="ot">&lt;-</span> daily_inc <span class="sc">|&gt;</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(geo, <span class="st">`</span><span class="at">2010</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">daily_income =</span> <span class="st">`</span><span class="at">2010</span><span class="st">`</span>)</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>landlocked <span class="ot">&lt;-</span> gap <span class="sc">|&gt;</span></span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(geo, name, landlocked)</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>full_2010 <span class="ot">&lt;-</span> cell_2010 <span class="sc">|&gt;</span></span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">full_join</span>(engy_2010, <span class="at">by =</span> <span class="st">"geo"</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">full_join</span>(landlocked, <span class="at">by =</span> <span class="st">"geo"</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">full_join</span>(hdi_2010, <span class="at">by =</span> <span class="st">"geo"</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">full_join</span>(mat_mort_2010, <span class="at">by =</span> <span class="st">"geo"</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">full_join</span>(daily_inc_2010, <span class="at">by =</span> <span class="st">"geo"</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(geo, name, cell_phones_per_100_ppl,</span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a>         residential_energy_use_pctg, landlocked,</span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a>         human_development_ind, maternal_mortality, daily_income)</span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a>clean_2010 <span class="ot">&lt;-</span> full_2010 <span class="sc">|&gt;</span></span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb18-36"><a href="#cb18-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-37"><a href="#cb18-37" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(clean_2010)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  geo   name      cell_phones_per_100_ppl residential_energy_use_pctg landlocked
  &lt;chr&gt; &lt;chr&gt;                       &lt;dbl&gt;                       &lt;dbl&gt; &lt;chr&gt;     
1 ago   Angola                       40.4                       57.0  coastline 
2 alb   Albania                      91.9                       25.0  coastline 
3 are   UAE                         157.                         6.35 coastline 
4 arg   Argentina                   138.                        22.8  coastline 
5 arm   Armenia                     132.                        30.0  landlocked
6 aus   Australia                   102.                        13.5  coastline 
# ℹ 3 more variables: human_development_ind &lt;dbl&gt;, maternal_mortality &lt;dbl&gt;,
#   daily_income &lt;dbl&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(clean_2010)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 132</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(clean_2010)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 132
Columns: 8
$ geo                         &lt;chr&gt; "ago", "alb", "are", "arg", "arm", "aus", …
$ name                        &lt;chr&gt; "Angola", "Albania", "UAE", "Argentina", "…
$ cell_phones_per_100_ppl     &lt;dbl&gt; 40.36676, 91.92993, 157.47258, 138.25164, …
$ residential_energy_use_pctg &lt;dbl&gt; 57.010, 25.030, 6.351, 22.800, 30.040, 13.…
$ landlocked                  &lt;chr&gt; "coastline", "coastline", "coastline", "co…
$ human_development_ind       &lt;dbl&gt; 0.528, 0.769, 0.835, 0.844, 0.747, 0.929, …
$ maternal_mortality          &lt;dbl&gt; 450, 27, 12, 77, 30, 7, 4, 43, 8, 350, 240…
$ daily_income                &lt;dbl&gt; 7.1482, 10.4012, 73.5858, 27.3047, 8.1821,…</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(clean_2010)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        geo             name     cell_phones_per_100_ppl
 Length   :132   Length   :132   Min.   :  1.212        
 N.unique :132   N.unique :132   1st Qu.: 70.437        
 N.blank  :  0   N.blank  :  0   Median :101.643        
 Min.nchar:  3   Min.nchar:  2   Mean   : 96.963        
 Max.nchar:  3   Max.nchar: 22   3rd Qu.:119.508        
                                 Max.   :204.969        
 residential_energy_use_pctg     landlocked  human_development_ind
 Min.   : 1.362              Length   :132   Min.   :0.4150       
 1st Qu.:17.777              N.unique :  2   1st Qu.:0.6518       
 Median :25.370              N.blank  :  0   Median :0.7505       
 Mean   :31.758              Min.nchar:  9   Mean   :0.7358       
 3rd Qu.:38.130              Max.nchar: 10   3rd Qu.:0.8458       
 Max.   :93.820                              Max.   :0.9470       
 maternal_mortality  daily_income    
 Min.   :  2.0      Min.   :  1.902  
 1st Qu.: 12.0      1st Qu.:  8.244  
 Median : 44.5      Median : 15.873  
 Mean   :114.9      Mean   : 26.577  
 3rd Qu.:127.5      3rd Qu.: 40.825  
 Max.   :730.0      Max.   :103.316  </code></pre>
</div>
</div>
</section>
<section id="saving-data-into-new-file" class="level3">
<h3 class="anchored" data-anchor-id="saving-data-into-new-file">Saving Data Into New File</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(clean_2010, <span class="st">"clean_2010.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="displaying-each-variable" class="level3">
<h3 class="anchored" data-anchor-id="displaying-each-variable">Displaying Each Variable</h3>
<section id="landlocked" class="level4">
<h4 class="anchored" data-anchor-id="landlocked">Landlocked</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(clean_2010<span class="sc">$</span>landlocked)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 coastline landlocked 
       108         24 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(clean_2010, <span class="fu">aes</span>(<span class="at">x =</span> landlocked)) <span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Landlocked vs. Coastline Countries (2010)"</span>,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Landlocked"</span>, <span class="at">y =</span> <span class="st">"Number of Countries"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DataPrep_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Of the 132, 108 (81.8%) have a coastline and 24 (18.2%) are landlocked. The bar chart shows that coastline countries outnumber landlocked countries by a lot.</p>
</section>
<section id="daily-income" class="level4">
<h4 class="anchored" data-anchor-id="daily-income">Daily Income</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(clean_2010, <span class="fu">aes</span>(<span class="at">x =</span> daily_income)) <span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Daily Income (2010)"</span>, <span class="at">x =</span> <span class="st">"Daily Income"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DataPrep_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>clean_2010 <span class="sc">|&gt;</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean   =</span> <span class="fu">mean</span>(daily_income),</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">median =</span> <span class="fu">median</span>(daily_income),</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd     =</span> <span class="fu">sd</span>(daily_income),</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">min    =</span> <span class="fu">min</span>(daily_income),</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">max    =</span> <span class="fu">max</span>(daily_income))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
   mean median    sd   min   max
  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1  26.6   15.9  24.3  1.90  103.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Six countries with the lowest values</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>clean_2010 <span class="sc">|&gt;</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(daily_income) <span class="sc">|&gt;</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(name, geo, daily_income) <span class="sc">|&gt;</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  name             geo   daily_income
  &lt;chr&gt;            &lt;chr&gt;        &lt;dbl&gt;
1 Congo, Dem. Rep. cod           1.90
2 Eritrea          eri           2.28
3 Mozambique       moz           2.57
4 Zambia           zmb           3.03
5 Benin            ben           3.11
6 Togo             tgo           3.17</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Six countries with the highest values (displayed in ascending order)</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>clean_2010 <span class="sc">|&gt;</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(daily_income) <span class="sc">|&gt;</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(name, geo, daily_income) <span class="sc">|&gt;</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tail</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  name        geo   daily_income
  &lt;chr&gt;       &lt;chr&gt;        &lt;dbl&gt;
1 USA         usa           75.5
2 Switzerland che           81.9
3 Luxembourg  lux           84.8
4 Brunei      brn           88.8
5 Qatar       qat           99.0
6 Singapore   sgp          103. </code></pre>
</div>
</div>
<p>Daily income is right-skewed: the mean is 26.58 per person per day, with a median of 15.87 and a standard deviation of 24.32 in income units. Most countries have lower incomes,a smaller number of high-income countries The Democratic Republic of the Congo has the lowest value (1.90), while Singapore (103.32) and Qatar (99.03) have the highest values.</p>
</section>
<section id="cell-phones-per-100-people" class="level4">
<h4 class="anchored" data-anchor-id="cell-phones-per-100-people">Cell Phones per 100 People</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(clean_2010, <span class="fu">aes</span>(<span class="at">x =</span> cell_phones_per_100_ppl)) <span class="sc">+</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Cell Phones per 100 People (2010)"</span>, <span class="at">x =</span> <span class="st">"Cell Phones"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DataPrep_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>clean_2010 <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean   =</span> <span class="fu">mean</span>(cell_phones_per_100_ppl),</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">median =</span> <span class="fu">median</span>(cell_phones_per_100_ppl),</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd     =</span> <span class="fu">sd</span>(cell_phones_per_100_ppl),</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">min    =</span> <span class="fu">min</span>(cell_phones_per_100_ppl),</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">max    =</span> <span class="fu">max</span>(cell_phones_per_100_ppl))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
   mean median    sd   min   max
  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1  97.0   102.  38.0  1.21  205.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Six countries with the lowest values</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>clean_2010 <span class="sc">|&gt;</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(cell_phones_per_100_ppl) <span class="sc">|&gt;</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(name, geo, cell_phones_per_100_ppl) <span class="sc">|&gt;</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  name             geo   cell_phones_per_100_ppl
  &lt;chr&gt;            &lt;chr&gt;                   &lt;dbl&gt;
1 Myanmar          mmr                      1.21
2 Eritrea          eri                      6.29
3 Ethiopia         eth                      7.57
4 Cuba             cub                      8.88
5 Congo, Dem. Rep. cod                     17.2 
6 Mozambique       moz                     31.4 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Six countries with the highest values (displayed in ascending order)</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>clean_2010 <span class="sc">|&gt;</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(cell_phones_per_100_ppl) <span class="sc">|&gt;</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(name, geo, cell_phones_per_100_ppl) <span class="sc">|&gt;</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tail</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  name         geo   cell_phones_per_100_ppl
  &lt;chr&gt;        &lt;chr&gt;                   &lt;dbl&gt;
1 Lithuania    ltu                      158.
2 Russia       rus                      165.
3 Libya        lby                      168.
4 Panama       pan                      183.
5 Montenegro   mne                      185.
6 Saudi Arabia sau                      205.</code></pre>
</div>
</div>
<p>The mean is 96.96 subscriptions per 100 people, the median is 101.64, and the standard deviation is 38.04. Myanmar has the lowest value (1.21), while Saudi Arabia has the highest (204.97);</p>
</section>
<section id="residential-energy-use-percentage" class="level4">
<h4 class="anchored" data-anchor-id="residential-energy-use-percentage">Residential Energy Use Percentage</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(clean_2010, <span class="fu">aes</span>(<span class="at">x =</span> residential_energy_use_pctg)) <span class="sc">+</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residential Energy Use Percentage (2010)"</span>, <span class="at">x =</span> <span class="st">"Residential Energy Use"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DataPrep_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>clean_2010 <span class="sc">|&gt;</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean   =</span> <span class="fu">mean</span>(residential_energy_use_pctg),</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">median =</span> <span class="fu">median</span>(residential_energy_use_pctg),</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd     =</span> <span class="fu">sd</span>(residential_energy_use_pctg),</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">min    =</span> <span class="fu">min</span>(residential_energy_use_pctg),</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">max    =</span> <span class="fu">max</span>(residential_energy_use_pctg))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
   mean median    sd   min   max
  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1  31.8   25.4  20.3  1.36  93.8</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Six countries with the lowest values</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>clean_2010 <span class="sc">|&gt;</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(residential_energy_use_pctg) <span class="sc">|&gt;</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(name, geo, residential_energy_use_pctg) <span class="sc">|&gt;</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  name                geo   residential_energy_use_pctg
  &lt;chr&gt;               &lt;chr&gt;                       &lt;dbl&gt;
1 Turkmenistan        tkm                          1.36
2 Trinidad and Tobago tto                          2.37
3 Singapore           sgp                          2.85
4 Qatar               qat                          3.65
5 Kyrgyz Republic     kgz                          5.00
6 UAE                 are                          6.35</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Six countries with the highest values (displayed in ascending order)</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>clean_2010 <span class="sc">|&gt;</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(residential_energy_use_pctg) <span class="sc">|&gt;</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(name, geo, residential_energy_use_pctg) <span class="sc">|&gt;</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tail</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  name     geo   residential_energy_use_pctg
  &lt;chr&gt;    &lt;chr&gt;                       &lt;dbl&gt;
1 Kenya    ken                          76.5
2 Eritrea  eri                          78.5
3 Myanmar  mmr                          80.7
4 Nigeria  nga                          81.1
5 Nepal    npl                          87.4
6 Ethiopia eth                          93.8</code></pre>
</div>
</div>
<p>Has a mean of 31.76%, a median of 25.37%, and a standard deviation of 20.33 . Most countries have smaller residential shares. Turkmenistan has the lowest share (1.36%), and Ethiopia has the highest (93.82%);</p>
</section>
<section id="maternal-mortality" class="level4">
<h4 class="anchored" data-anchor-id="maternal-mortality">Maternal Mortality</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(clean_2010, <span class="fu">aes</span>(<span class="at">x =</span> maternal_mortality)) <span class="sc">+</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Maternal Mortality (2010)"</span>, <span class="at">x =</span> <span class="st">"Maternal Deaths per 100,000 Births"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DataPrep_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>clean_2010 <span class="sc">|&gt;</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean   =</span> <span class="fu">mean</span>(maternal_mortality),</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">median =</span> <span class="fu">median</span>(maternal_mortality),</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd     =</span> <span class="fu">sd</span>(maternal_mortality),</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">min    =</span> <span class="fu">min</span>(maternal_mortality),</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">max    =</span> <span class="fu">max</span>(maternal_mortality))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
   mean median    sd   min   max
  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1  115.   44.5  161.     2   730</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Six countries with the lowest values</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>clean_2010 <span class="sc">|&gt;</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(maternal_mortality) <span class="sc">|&gt;</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(name, geo, maternal_mortality) <span class="sc">|&gt;</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  name      geo   maternal_mortality
  &lt;chr&gt;     &lt;chr&gt;              &lt;dbl&gt;
1 Estonia   est                    2
2 Greece    grc                    3
3 Singapore sgp                    3
4 Austria   aut                    4
5 Belarus   blr                    4
6 Italy     ita                    4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Six countries with the highest values (displayed in ascending order)</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>clean_2010 <span class="sc">|&gt;</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(maternal_mortality) <span class="sc">|&gt;</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(name, geo, maternal_mortality) <span class="sc">|&gt;</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tail</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  name             geo   maternal_mortality
  &lt;chr&gt;            &lt;chr&gt;              &lt;dbl&gt;
1 Congo, Dem. Rep. cod                  540
2 Congo, Rep.      cog                  560
3 Zimbabwe         zwe                  570
4 Nigeria          nga                  630
5 Cameroon         cmr                  690
6 Sudan            sdn                  730</code></pre>
</div>
</div>
<p>Maternal mortality is strongly right-skewed: the mean is 114.92 deaths per 100,000 live births, compared with a median of 44.50 and a standard deviation of 160.82. Many countries have relatively low ratios. Estonia has the lowest ratio (2), and Sudan has the highest (730).</p>
</section>
<section id="hdi" class="level4">
<h4 class="anchored" data-anchor-id="hdi">HDI</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(clean_2010, <span class="fu">aes</span>(<span class="at">x =</span> human_development_ind)) <span class="sc">+</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Human Development Index (2010)"</span>, <span class="at">x =</span> <span class="st">"HDI"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DataPrep_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>clean_2010 <span class="sc">|&gt;</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean   =</span> <span class="fu">mean</span>(human_development_ind),</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">median =</span> <span class="fu">median</span>(human_development_ind),</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd     =</span> <span class="fu">sd</span>(human_development_ind),</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">min    =</span> <span class="fu">min</span>(human_development_ind),</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">max    =</span> <span class="fu">max</span>(human_development_ind))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
   mean median    sd   min   max
  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 0.736  0.750 0.143 0.415 0.947</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Six countries with the lowest values</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>clean_2010 <span class="sc">|&gt;</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(human_development_ind) <span class="sc">|&gt;</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(name, geo, human_development_ind) <span class="sc">|&gt;</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  name             geo   human_development_ind
  &lt;chr&gt;            &lt;chr&gt;                 &lt;dbl&gt;
1 Ethiopia         eth                   0.415
2 Mozambique       moz                   0.419
3 Congo, Dem. Rep. cod                   0.44 
4 Haiti            hti                   0.452
5 Cote d'Ivoire    civ                   0.465
6 Eritrea          eri                   0.465</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Six countries with the highest values (displayed in ascending order)</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>clean_2010 <span class="sc">|&gt;</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(human_development_ind) <span class="sc">|&gt;</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(name, geo, human_development_ind) <span class="sc">|&gt;</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tail</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  name        geo   human_development_ind
  &lt;chr&gt;       &lt;chr&gt;                 &lt;dbl&gt;
1 Australia   aus                   0.929
2 Singapore   sgp                   0.932
3 Iceland     isl                   0.935
4 Germany     deu                   0.936
5 Switzerland che                   0.945
6 Norway      nor                   0.947</code></pre>
</div>
</div>
<p>HDI has a mean of 0.736, a median of 0.751, and a standard deviation of 0.143. Values are more concentrated toward the higher end, with a tail toward lower development scores.</p>
</section>
</section>
<section id="displaying-graphs-of-each-variable-related-to-one-another" class="level3">
<h3 class="anchored" data-anchor-id="displaying-graphs-of-each-variable-related-to-one-another">Displaying Graphs of Each Variable Related to One Another</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(clean_2010[<span class="fu">c</span>(</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"cell_phones_per_100_ppl"</span>,</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"residential_energy_use_pctg"</span>,</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"human_development_ind"</span>,</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"maternal_mortality"</span>,</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"daily_income"</span></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>)])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DataPrep_files/figure-html/EDA-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The bottom row of the scatterplot matrix shows daily income against each quantitative predictor. These plots describe associations among the retained countries</p>
<p><strong>Cell phones and income:</strong> Countries with more cell-phone subscriptions per 100 people have higher daily income. income varies considerably among countries with similar especially at higher rates.</p>
<p><strong>Residential energy share and income:</strong> Higher residential energy shares are generally associated with lower daily income. The pattern is not well described by a uniform straight-line decrease across the entire range.</p>
<p><strong>HDI and income:</strong> Income generally increases with HDI.</p>
<p><strong>Maternal mortality and income:</strong> Countries with higher maternal mortality generally have lower income. Many countries have low maternal mortality but different incomes.</p>
<section id="daily-income-by-landlocked-status" class="level4">
<h4 class="anchored" data-anchor-id="daily-income-by-landlocked-status">Daily Income by Landlocked Status</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>clean_2010 <span class="sc">|&gt;</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(landlocked) <span class="sc">|&gt;</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">countries =</span> <span class="fu">n</span>(),</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean_income =</span> <span class="fu">mean</span>(daily_income),</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">median_income =</span> <span class="fu">median</span>(daily_income),</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd_income =</span> <span class="fu">sd</span>(daily_income))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  landlocked countries mean_income median_income sd_income
  &lt;chr&gt;          &lt;int&gt;       &lt;dbl&gt;         &lt;dbl&gt;     &lt;dbl&gt;
1 coastline        108        27.8          16.9      24.3
2 landlocked        24        21.2          12.3      24.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>clean_2010 <span class="sc">|&gt;</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> landlocked, <span class="at">y =</span> daily_income)) <span class="sc">+</span></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Daily Income by Landlocked Status (2010)"</span>,</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Landlocked status"</span>, <span class="at">y =</span> <span class="st">"Daily income per person"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DataPrep_files/figure-html/income%20by%20landlocked%20status-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Coastline countries have a higher mean daily income (27.77) and median (16.85) than landlocked countries (21.20 and 12.29), . The standard deviations are close 24.27 for coastline countries and 24.34 for landlocked countries. The violin plot shows overlap, so landlocked status does not clearly separate countries. There are 108 coastline countries and only 24 landlocked countries in this sample.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>transformed_2010 <span class="ot">&lt;-</span> clean_2010 <span class="sc">|&gt;</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">log_daily_income =</span> <span class="fu">log</span>(daily_income),</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">log_energy       =</span> <span class="fu">log</span>(<span class="dv">1</span> <span class="sc">+</span> residential_energy_use_pctg),</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">log_mortality    =</span> <span class="fu">log</span>(<span class="dv">1</span> <span class="sc">+</span> maternal_mortality)</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="creating-log-of-data" class="level3">
<h3 class="anchored" data-anchor-id="creating-log-of-data">Creating Log of Data</h3>
<p>All three models below predict natural-log income. For a predictor on its original scale, a one-unit increase changes predicted log income by its coefficient, holding the other predictors fixed. On the income scale, exponentiating that coefficient gives the multiplicative change in the model’s back transformed prediction. A coefficient on log energy or log mortality describes a one-unit change in the log of <code>1 +</code> the original measurement, not a one-unit change in the original measurement. The landlocked coefficient compares landlocked countries with coastline countries. We will apply these interpretations to the fitted coefficients in the model discussion; simply exponentiating a fitted log value does not automatically give the conditional arithmetic mean of income.</p>
</section>
<section id="making-lines-of-regression" class="level3">
<h3 class="anchored" data-anchor-id="making-lines-of-regression">Making Lines of Regression</h3>
<p>We fit two multiple regressions and one simple regression to the same 132 countries. Each model predicts natural-log daily income, so its residual standard error (RSE) is in log-income units, not dollars. R-squared describes the fraction of variation in log income explained by the fitted model; adjusted R-squared also accounts for the number of predictors. We use 0.05 as the cutoff when discussing p-values. An overall F-test checks whether all predictor slopes are zero; a small p-value does not prove that the model meets its assumptions.</p>
<p>For all three models, independence is an assumption we cannot confirm from the diagnostic plots. Each row is a different country, but countries may share regional, economic, and historical conditions. We therefore interpret these results as associations in the retained countries, not causal effects, and treat the p-values cautiously when the model assumptions are imperfect.</p>
<section id="model-1-logdaily-income-vs-all-five-predictors" class="level4">
<h4 class="anchored" data-anchor-id="model-1-logdaily-income-vs-all-five-predictors">Model 1: Log(Daily Income) vs All Five Predictors</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>income_model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>  log_daily_income <span class="sc">~</span> cell_phones_per_100_ppl <span class="sc">+</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>    log_energy <span class="sc">+</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>    human_development_ind <span class="sc">+</span></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>    log_mortality <span class="sc">+</span></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>    landlocked,</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> transformed_2010</span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(income_model1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_daily_income ~ cell_phones_per_100_ppl + log_energy + 
    human_development_ind + log_mortality + landlocked, data = transformed_2010)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.10707 -0.24517 -0.00101  0.23675  0.90273 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             -0.127473   0.744523  -0.171  0.86433    
cell_phones_per_100_ppl  0.001961   0.001300   1.509  0.13383    
log_energy              -0.166634   0.065416  -2.547  0.01206 *  
human_development_ind    4.880395   0.658284   7.414 1.57e-11 ***
log_mortality           -0.057311   0.057950  -0.989  0.32456    
landlockedlandlocked    -0.261677   0.090396  -2.895  0.00447 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3993 on 126 degrees of freedom
Multiple R-squared:  0.8431,    Adjusted R-squared:  0.8368 
F-statistic: 135.4 on 5 and 126 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(income_model1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DataPrep_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Interpreting the slopes.</strong> Holding the other predictors fixed:</p>
<ul>
<li>One additional cell-phone subscription per 100 people is associated with an increase of 0.00196 in predicted log income, or about 0.20% in the back-transformed income prediction.</li>
<li>A one dunit increase in log(1 + residential energy share) is associated with a decrease of 0.1666 in predicted log income. This is a change in the logged predictor, not a one-percentage-point increase in energy share.</li>
<li>A 0.1 increase in HDI is associated with an increase of 0.4880 in predicted log income, equivalent to about a 62.9% increase in the back-transformed prediction.</li>
<li>A oneunit increase in log(1 + maternal mortality) is associated with a decrease of 0.0573 in predicted log income, not a decrease of 0.0573 dollars.</li>
<li>Landlocked countries have predicted log income 0.2617 lower than coastline countries, equivalent to about a 23.0% lower back transformed prediction.</li>
</ul>
<p><strong>Model fit.</strong> The model explains 84.31% of the variation in log income (adjusted R-squared = 0.8368), with an RSE of 0.3993. Ts p &lt; 0.001, at least one predictor slope differs from zero. Energy (p = 0.0121), HDI (p &lt; 0.001), and landlocked status (p = 0.0045) are significant at 0.05. Cell phones (p = 0.1338) and mortality (p = 0.3246) are not significant after adjusting for the other predictors.</p>
<p><strong>LINE</strong> The residual plot has a curved, roughly U-shaped trend, so the linearity assumption is not fully satisfied. The Q–Q plot follows the line through most of its range but not at the tails. The scale location plot shows greater spread in the middle. Normality and equal variance are almost, and the independence concern described above still applies. The model fits much of the variation, but its residual pattern shows that it isnt perfect.</p>
</section>
<section id="model-2-logdaily-income-vs-log-energy-and-landlocked-status" class="level4">
<h4 class="anchored" data-anchor-id="model-2-logdaily-income-vs-log-energy-and-landlocked-status">Model 2: Log(Daily Income) vs Log Energy and Landlocked Status</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>income_model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  log_daily_income <span class="sc">~</span> log_energy <span class="sc">+</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>    landlocked,</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> transformed_2010</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(income_model2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_daily_income ~ log_energy + landlocked, data = transformed_2010)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.38507 -0.58462 -0.00221  0.55654  1.95616 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            5.8527     0.3435  17.037  &lt; 2e-16 ***
log_energy            -0.8989     0.1021  -8.806 7.39e-15 ***
landlockedlandlocked  -0.2969     0.1761  -1.685   0.0943 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7802 on 129 degrees of freedom
Multiple R-squared:  0.3866,    Adjusted R-squared:  0.3771 
F-statistic: 40.65 on 2 and 129 DF,  p-value: 2.043e-14</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(income_model2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DataPrep_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Interpreting the slopes.</strong> Holding landlocked status fixed, a increase in log(1 + residential energy share) is associated with a decrease of 0.8989 in log income. landlocked countries have predicted log income 0.2969 lower than coastline countries. The intercept 5.8527 applies to a coastline country with zero residential energy share</p>
<p><strong>Model fit.</strong> The model explains 38.66% of the variation in log income (adjusted R-squared = 0.3771), with an RSE of 0.7802. Its overall F-test has p &lt; 0.001. The energy slope is significant (p &lt; 0.001), but the landlocked slope is not significant at 0.05 (p = 0.0943).</p>
<p><strong>Assumptions.</strong> The residual trend goes up and then down. Most points in the Q–Q plot follow the line, but the lower tail some that done. The residual spread is uneven so equal variance is not established.</p>
</section>
<section id="model-3-logdaily-income-vs-hdi" class="level4">
<h4 class="anchored" data-anchor-id="model-3-logdaily-income-vs-hdi">Model 3: Log(Daily Income) vs HDI</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>income_model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>  log_daily_income <span class="sc">~</span> human_development_ind,</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> transformed_2010</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(income_model3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_daily_income ~ human_development_ind, data = transformed_2010)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.33415 -0.28607  0.01349  0.23971  1.14232 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            -1.7637     0.1932  -9.129 1.15e-15 ***
human_development_ind   6.2551     0.2578  24.266  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.422 on 130 degrees of freedom
Multiple R-squared:  0.8192,    Adjusted R-squared:  0.8178 
F-statistic: 588.8 on 1 and 130 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(income_model3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DataPrep_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Interpreting the slope.</strong> A 0.1 increase in HDI is associated with an increase of 0.6255 in predicted log income, equivalent to about an 86.9% increase. The intercept is -1.7637, the predicted log income at HDI = 0, which is outside the observed HDI range and is not a meaningful comparison for these countries.</p>
<p><strong>Model fit.</strong> HDI alone explains 81.92% of the variation in log income adjusted R-squared = 0.8178), with an RSE of 0.4220. Both the HDI slope test and the overall F-test have p &lt; 0.001. This is strong evidence of an association within this fitted model</p>
<p><strong>Assumptions.</strong> The residual trend has a shallow curve, so the relationship is close to linear but not perfect. The Q–Q plot is close to the line in the middle and departs at both tails. The scale-location plot shows more spread in the middle and less at the high end so equal variance isnt clear.</p>
</section>
</section>
<section id="comparing-the-models" class="level3">
<h3 class="anchored" data-anchor-id="comparing-the-models">Comparing the Models</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">Number of predictors</th>
<th style="text-align: right;">Adjusted R-squared</th>
<th style="text-align: right;">Residual standard error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model 1: All five predictors</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.8368</td>
<td style="text-align: right;">0.3993</td>
</tr>
<tr class="even">
<td>Model 2: Log energy and landlocked status</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.3771</td>
<td style="text-align: right;">0.7802</td>
</tr>
<tr class="odd">
<td>Model 3: HDI alone</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.8178</td>
<td style="text-align: right;">0.4220</td>
</tr>
</tbody>
</table>
<p><strong>We prefer Model 1 for its fit to these data.</strong> It has the highest adjusted R-squared, and the lowest residual standard error. Model 3 is also good. HDI gives a similar fit with only one predictor, making Model 3 a solid choice when simplicity is the priority. Model 2 explains much less variation and has substantially more residual scatter, so it is the weakest of the three by these measures.</p>
<p>The diagnostic plots keep us from treating any model as a perfect fit. Model 1 still has curvature in its residuals, and Model 3 has some curvature and uneven spread as well. Model 2 shows curvature and a particularly influential observation. We choose Model 1 for its better overall fit.</p>
</section>
<section id="our-question" class="level3">
<h3 class="anchored" data-anchor-id="our-question">Our Question</h3>
<p><strong>Does the relationship between HDI and daily income look similar for landlocked and coastline countries?</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>transformed_2010 <span class="sc">|&gt;</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> human_development_ind,</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">y =</span> log_daily_income,</span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">color =</span> landlocked)) <span class="sc">+</span></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"HDI and Daily Income by Landlocked Status (2010)"</span>,</span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Human Development Index (HDI)"</span>,</span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Log daily income (natural log)"</span>,</span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Country type"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DataPrep_files/figure-html/our%20question-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Our answer:</strong> Yes, the overall pattern looks similar countries with higher HDI generally have higher income in both groups. The colors overlap insead of forming two clearly separate groups. Several landlocked countries have both high HDI and high income, so being landlocked does not automatically mean a country has low income. Some landlocked countries fall below coastline countries with similar HDI, but that is not true everywhere in the plot. There are also fewer landlocked countries in the sample. The graph supports a shared positive pattern, but it does not prove that the relationships are identical or that landlocked status causes income differences.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>